### PR TITLE
Add SOBP Annotations, and option to return locations

### PR DESCRIPTION
**Pull request by adelavega**
- Adds SOBP annotations for a few participants
- Adds option to return characters location for annotations

### CODE REVIEW

**Comment by adelavega** [comment]
Not sure why but when I do this

```
subgroups = get_participant_demographics()
```

I don't get all the annotations, including "jennifer_siegel". 

I have reset the database.

**Comment by adelavega** [comment]
Ah, I think it's because that annotator had errors in all their annotations

e.g.
image

**Comment by adelavega** [comment]
I started a notebook to evaluate inter-rater agreement, not sure if there was already something like this

https://github.com/adelavega/biomed-llm-retrieval/blob/master/participant_demographics_rateragreement.ipynb

I can clean up and merge here if there's interest

**Comment by jeromedockes** [comment]
thanks! indeed `get_participant_demographics` will only grap the "correct" annotations -- I realize the annotation process is a bit complex.

**Comment by jeromedockes** [comment]
> I started a notebook to evaluate inter-rater agreement, not sure if there was already something like this

there isn't yet; it would be great to have something like this in the repo's jupyter book. I get a 404 error when I try to follow the link, is it a private repo?

**Comment by adelavega** [comment]
Sorry I just moved the file: https://github.com/adelavega/biomed-llm-retrieval/blob/master/analysis/pd_rateragreement.ipynb

**Pull request merged**
